/*
Kubernetes Operator Controller Skeleton for GrafanaDashboard

This file demonstrates the structure of a Kubernetes operator controller using
the controller-runtime library. The operator pattern extends Kubernetes to manage
custom resources (like GrafanaDashboard) through a reconciliation loop.

Key Concepts:
- Reconciliation Loop: The core pattern where the controller continuously works
  to make the actual state match the desired state defined in the custom resource.
- Controller-Runtime: The standard library for building Kubernetes operators in Go,
  providing abstractions for watches, caches, and reconciliation.
- Finalizers: Allow cleanup of external resources when a custom resource is deleted.

This pattern is commonly used in Grafana's ecosystem, including:
- Grafana Operator: Manages Grafana instances and dashboards
- Loki Operator: Manages Loki deployments
- Tempo Operator: Manages Tempo distributed tracing

Usage:
  This is a skeleton/reference implementation. To build a complete operator:
  1. Use kubebuilder or operator-sdk to scaffold the project
  2. Generate CRD manifests and RBAC rules
  3. Implement the reconciliation logic
  4. Build and deploy to your cluster

References:
- https://book.kubebuilder.io/
- https://sdk.operatorframework.io/
- https://github.com/grafana/grafana-operator
*/

package controllers

import (
	"context"
	"fmt"
	"time"

	"github.com/go-logr/logr"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/client-go/tools/record"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	"sigs.k8s.io/controller-runtime/pkg/predicate"

	// Import the API types for our custom resource
	// In a real project, this would be generated by kubebuilder
	observabilityv1alpha1 "github.com/example/grafana-operator/api/v1alpha1"
)

// ============================================================================
// Constants
// ============================================================================

const (
	// FinalizerName is used to ensure cleanup when the resource is deleted
	// Finalizers prevent deletion until the controller has cleaned up external resources
	FinalizerName = "grafanadashboard.observability.grafana.com/finalizer"

	// DefaultRequeueAfter is the default time to wait before requeuing
	DefaultRequeueAfter = 5 * time.Minute

	// ErrorRequeueAfter is the time to wait before requeuing after an error
	ErrorRequeueAfter = 30 * time.Second
)

// Condition types for status reporting
const (
	// ConditionTypeSynced indicates whether the dashboard is synced to Grafana
	ConditionTypeSynced = "Synced"

	// ConditionTypeReady indicates whether the dashboard is ready for use
	ConditionTypeReady = "Ready"

	// ConditionTypeDegraded indicates the dashboard is in a degraded state
	ConditionTypeDegraded = "Degraded"
)

// Condition reasons provide machine-readable explanations
const (
	ReasonSyncSuccess     = "SyncSuccess"
	ReasonSyncFailed      = "SyncFailed"
	ReasonGrafanaNotFound = "GrafanaNotFound"
	ReasonInvalidSpec     = "InvalidSpec"
	ReasonReconciling     = "Reconciling"
)

// ============================================================================
// Controller Struct
// ============================================================================

// GrafanaDashboardReconciler reconciles a GrafanaDashboard object
// This struct holds all dependencies needed for reconciliation
type GrafanaDashboardReconciler struct {
	// Client is the Kubernetes API client for reading/writing resources
	// It provides caching and is the primary way to interact with the cluster
	client.Client

	// Scheme contains the API type definitions
	// Used for setting owner references and type conversions
	Scheme *runtime.Scheme

	// Log is the logger for this controller
	// Use structured logging with key-value pairs
	Log logr.Logger

	// Recorder is used to emit Kubernetes events
	// Events provide visibility into controller actions
	Recorder record.EventRecorder

	// GrafanaClient is a client for interacting with Grafana's HTTP API
	// In a real implementation, this would handle dashboard CRUD operations
	GrafanaClient GrafanaClient
}

// GrafanaClient interface defines operations for interacting with Grafana
// This abstraction allows for easy testing with mock implementations
type GrafanaClient interface {
	// CreateOrUpdateDashboard creates or updates a dashboard in Grafana
	CreateOrUpdateDashboard(ctx context.Context, dashboard *Dashboard) (*DashboardResponse, error)

	// DeleteDashboard removes a dashboard from Grafana
	DeleteDashboard(ctx context.Context, uid string) error

	// GetDashboard retrieves a dashboard by UID
	GetDashboard(ctx context.Context, uid string) (*Dashboard, error)
}

// Dashboard represents a Grafana dashboard for API operations
type Dashboard struct {
	UID     string
	Title   string
	Folder  string
	JSON    string
	Version int
}

// DashboardResponse contains the response from Grafana after dashboard operations
type DashboardResponse struct {
	UID     string
	URL     string
	Version int
}

// ============================================================================
// RBAC Markers
// ============================================================================

// These markers generate RBAC rules in the ClusterRole manifest
// They define what permissions the controller needs to operate

//+kubebuilder:rbac:groups=observability.grafana.com,resources=grafanadashboards,verbs=get;list;watch;create;update;patch;delete
//+kubebuilder:rbac:groups=observability.grafana.com,resources=grafanadashboards/status,verbs=get;update;patch
//+kubebuilder:rbac:groups=observability.grafana.com,resources=grafanadashboards/finalizers,verbs=update
//+kubebuilder:rbac:groups="",resources=configmaps,verbs=get;list;watch
//+kubebuilder:rbac:groups="",resources=secrets,verbs=get;list;watch
//+kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// ============================================================================
// Reconcile Function - The Heart of the Operator
// ============================================================================

// Reconcile is the main reconciliation loop for the GrafanaDashboard controller.
//
// The reconciliation pattern:
// 1. Fetch the custom resource
// 2. Check if it's being deleted (handle finalizers)
// 3. Validate the spec
// 4. Perform the actual work (sync to Grafana)
// 5. Update the status
// 6. Return result (requeue if needed)
//
// Key principles:
// - Idempotent: Running reconcile multiple times should produce the same result
// - Level-triggered: React to the current state, not events
// - Eventually consistent: Keep trying until desired state is achieved
func (r *GrafanaDashboardReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	log := r.Log.WithValues("grafanadashboard", req.NamespacedName)
	log.Info("Starting reconciliation")

	// -------------------------------------------------------------------------
	// Step 1: Fetch the GrafanaDashboard resource
	// -------------------------------------------------------------------------
	dashboard := &observabilityv1alpha1.GrafanaDashboard{}
	if err := r.Get(ctx, req.NamespacedName, dashboard); err != nil {
		if errors.IsNotFound(err) {
			// Resource was deleted before reconciliation
			// This is normal - just log and return without error
			log.Info("GrafanaDashboard resource not found, likely deleted")
			return ctrl.Result{}, nil
		}
		// Error reading the resource - requeue with backoff
		log.Error(err, "Failed to fetch GrafanaDashboard")
		return ctrl.Result{RequeueAfter: ErrorRequeueAfter}, err
	}

	// -------------------------------------------------------------------------
	// Step 2: Handle deletion with finalizers
	// -------------------------------------------------------------------------
	// Finalizers ensure we clean up external resources (Grafana dashboards)
	// before the Kubernetes resource is fully deleted

	if dashboard.ObjectMeta.DeletionTimestamp.IsZero() {
		// Resource is not being deleted
		// Ensure our finalizer is present
		if !controllerutil.ContainsFinalizer(dashboard, FinalizerName) {
			log.Info("Adding finalizer")
			controllerutil.AddFinalizer(dashboard, FinalizerName)
			if err := r.Update(ctx, dashboard); err != nil {
				log.Error(err, "Failed to add finalizer")
				return ctrl.Result{}, err
			}
			// Requeue to continue reconciliation with the updated resource
			return ctrl.Result{Requeue: true}, nil
		}
	} else {
		// Resource is being deleted
		if controllerutil.ContainsFinalizer(dashboard, FinalizerName) {
			log.Info("Handling deletion, cleaning up external resources")

			// Clean up the dashboard in Grafana
			if err := r.cleanupDashboard(ctx, dashboard); err != nil {
				log.Error(err, "Failed to cleanup dashboard in Grafana")
				// Record event for visibility
				r.Recorder.Event(dashboard, corev1.EventTypeWarning, "CleanupFailed",
					fmt.Sprintf("Failed to delete dashboard from Grafana: %v", err))
				return ctrl.Result{RequeueAfter: ErrorRequeueAfter}, err
			}

			// Remove the finalizer to allow deletion to proceed
			log.Info("Removing finalizer")
			controllerutil.RemoveFinalizer(dashboard, FinalizerName)
			if err := r.Update(ctx, dashboard); err != nil {
				log.Error(err, "Failed to remove finalizer")
				return ctrl.Result{}, err
			}

			r.Recorder.Event(dashboard, corev1.EventTypeNormal, "Deleted",
				"Dashboard successfully deleted from Grafana")
		}
		// Stop reconciliation as the resource is being deleted
		return ctrl.Result{}, nil
	}

	// -------------------------------------------------------------------------
	// Step 3: Validate the spec
	// -------------------------------------------------------------------------
	if err := r.validateSpec(dashboard); err != nil {
		log.Error(err, "Invalid GrafanaDashboard spec")
		r.Recorder.Event(dashboard, corev1.EventTypeWarning, "ValidationFailed", err.Error())

		// Update status to reflect the error
		if statusErr := r.updateStatus(ctx, dashboard, ConditionTypeSynced, metav1.ConditionFalse,
			ReasonInvalidSpec, err.Error()); statusErr != nil {
			log.Error(statusErr, "Failed to update status")
		}

		// Don't requeue - spec needs to be fixed by user
		return ctrl.Result{}, nil
	}

	// -------------------------------------------------------------------------
	// Step 4: Resolve dashboard JSON content
	// -------------------------------------------------------------------------
	// Dashboard JSON can come from multiple sources:
	// - Inline in spec.json
	// - From a ConfigMap reference
	// - From a URL
	// - From grafana.com

	dashboardJSON, err := r.resolveDashboardJSON(ctx, dashboard)
	if err != nil {
		log.Error(err, "Failed to resolve dashboard JSON")
		r.Recorder.Event(dashboard, corev1.EventTypeWarning, "ResolveFailed",
			fmt.Sprintf("Failed to resolve dashboard JSON: %v", err))

		if statusErr := r.updateStatus(ctx, dashboard, ConditionTypeSynced, metav1.ConditionFalse,
			ReasonSyncFailed, err.Error()); statusErr != nil {
			log.Error(statusErr, "Failed to update status")
		}

		return ctrl.Result{RequeueAfter: ErrorRequeueAfter}, err
	}

	// -------------------------------------------------------------------------
	// Step 5: Sync dashboard to Grafana
	// -------------------------------------------------------------------------
	log.Info("Syncing dashboard to Grafana", "title", dashboard.Spec.Title)

	grafanaDashboard := &Dashboard{
		UID:    dashboard.Status.UID, // Use existing UID if available
		Title:  dashboard.Spec.Title,
		Folder: dashboard.Spec.Folder,
		JSON:   dashboardJSON,
	}

	response, err := r.GrafanaClient.CreateOrUpdateDashboard(ctx, grafanaDashboard)
	if err != nil {
		log.Error(err, "Failed to sync dashboard to Grafana")
		r.Recorder.Event(dashboard, corev1.EventTypeWarning, "SyncFailed",
			fmt.Sprintf("Failed to sync dashboard: %v", err))

		if statusErr := r.updateStatus(ctx, dashboard, ConditionTypeSynced, metav1.ConditionFalse,
			ReasonSyncFailed, err.Error()); statusErr != nil {
			log.Error(statusErr, "Failed to update status")
		}

		return ctrl.Result{RequeueAfter: ErrorRequeueAfter}, err
	}

	// -------------------------------------------------------------------------
	// Step 6: Update status with success
	// -------------------------------------------------------------------------
	log.Info("Dashboard synced successfully", "uid", response.UID, "url", response.URL)

	// Update status fields
	dashboard.Status.UID = response.UID
	dashboard.Status.URL = response.URL
	dashboard.Status.LastSyncTime = &metav1.Time{Time: time.Now()}
	dashboard.Status.ObservedGeneration = dashboard.Generation

	// Calculate content hash for change detection
	dashboard.Status.ContentHash = calculateHash(dashboardJSON)

	// Update the synced condition
	if err := r.updateStatus(ctx, dashboard, ConditionTypeSynced, metav1.ConditionTrue,
		ReasonSyncSuccess, "Dashboard successfully synced to Grafana"); err != nil {
		log.Error(err, "Failed to update status")
		return ctrl.Result{}, err
	}

	// Record success event
	r.Recorder.Event(dashboard, corev1.EventTypeNormal, "Synced",
		fmt.Sprintf("Dashboard synced to Grafana: %s", response.URL))

	// -------------------------------------------------------------------------
	// Step 7: Schedule next reconciliation
	// -------------------------------------------------------------------------
	// Requeue after the configured resync period to ensure the dashboard
	// stays in sync (handles manual changes in Grafana UI)

	requeueAfter := DefaultRequeueAfter
	if dashboard.Spec.ResyncPeriod != "" {
		if parsed, err := time.ParseDuration(dashboard.Spec.ResyncPeriod); err == nil {
			requeueAfter = parsed
		}
	}

	log.Info("Reconciliation complete, scheduling next sync", "requeueAfter", requeueAfter)
	return ctrl.Result{RequeueAfter: requeueAfter}, nil
}

// ============================================================================
// Helper Functions
// ============================================================================

// validateSpec validates the GrafanaDashboard spec
func (r *GrafanaDashboardReconciler) validateSpec(dashboard *observabilityv1alpha1.GrafanaDashboard) error {
	// Ensure at least one JSON source is specified
	hasJSON := dashboard.Spec.JSON != ""
	hasConfigMapRef := dashboard.Spec.JSONDataFrom != nil && dashboard.Spec.JSONDataFrom.ConfigMapKeyRef != nil
	hasURL := dashboard.Spec.URL != ""
	hasGrafanaCom := dashboard.Spec.GrafanaCom != nil

	sourceCount := 0
	if hasJSON {
		sourceCount++
	}
	if hasConfigMapRef {
		sourceCount++
	}
	if hasURL {
		sourceCount++
	}
	if hasGrafanaCom {
		sourceCount++
	}

	if sourceCount == 0 {
		return fmt.Errorf("must specify one of: json, jsonDataFrom, url, or grafanaCom")
	}
	if sourceCount > 1 {
		return fmt.Errorf("only one JSON source can be specified")
	}

	// Validate instance selector
	if dashboard.Spec.InstanceSelector == nil {
		return fmt.Errorf("instanceSelector is required")
	}

	return nil
}

// resolveDashboardJSON resolves the dashboard JSON from the configured source
func (r *GrafanaDashboardReconciler) resolveDashboardJSON(ctx context.Context, dashboard *observabilityv1alpha1.GrafanaDashboard) (string, error) {
	// Priority: inline JSON > ConfigMap > URL > grafana.com

	// 1. Inline JSON
	if dashboard.Spec.JSON != "" {
		return dashboard.Spec.JSON, nil
	}

	// 2. ConfigMap reference
	if dashboard.Spec.JSONDataFrom != nil && dashboard.Spec.JSONDataFrom.ConfigMapKeyRef != nil {
		ref := dashboard.Spec.JSONDataFrom.ConfigMapKeyRef
		namespace := dashboard.Namespace
		if ref.Namespace != "" {
			namespace = ref.Namespace
		}

		configMap := &corev1.ConfigMap{}
		if err := r.Get(ctx, types.NamespacedName{
			Name:      ref.Name,
			Namespace: namespace,
		}, configMap); err != nil {
			return "", fmt.Errorf("failed to get ConfigMap %s/%s: %w", namespace, ref.Name, err)
		}

		json, ok := configMap.Data[ref.Key]
		if !ok {
			return "", fmt.Errorf("key %s not found in ConfigMap %s/%s", ref.Key, namespace, ref.Name)
		}

		return json, nil
	}

	// 3. URL (would need HTTP client implementation)
	if dashboard.Spec.URL != "" {
		// In a real implementation, fetch from URL
		return "", fmt.Errorf("URL source not implemented in this skeleton")
	}

	// 4. grafana.com (would need grafana.com API client)
	if dashboard.Spec.GrafanaCom != nil {
		// In a real implementation, fetch from grafana.com
		return "", fmt.Errorf("grafana.com source not implemented in this skeleton")
	}

	return "", fmt.Errorf("no JSON source configured")
}

// cleanupDashboard removes the dashboard from Grafana
func (r *GrafanaDashboardReconciler) cleanupDashboard(ctx context.Context, dashboard *observabilityv1alpha1.GrafanaDashboard) error {
	if dashboard.Status.UID == "" {
		// No UID means dashboard was never created in Grafana
		return nil
	}

	return r.GrafanaClient.DeleteDashboard(ctx, dashboard.Status.UID)
}

// updateStatus updates the status conditions of the GrafanaDashboard
func (r *GrafanaDashboardReconciler) updateStatus(
	ctx context.Context,
	dashboard *observabilityv1alpha1.GrafanaDashboard,
	conditionType string,
	status metav1.ConditionStatus,
	reason, message string,
) error {
	// Find existing condition or create new one
	condition := metav1.Condition{
		Type:               conditionType,
		Status:             status,
		ObservedGeneration: dashboard.Generation,
		LastTransitionTime: metav1.Now(),
		Reason:             reason,
		Message:            message,
	}

	// Update or append the condition
	found := false
	for i, c := range dashboard.Status.Conditions {
		if c.Type == conditionType {
			// Only update LastTransitionTime if status changed
			if c.Status != status {
				dashboard.Status.Conditions[i] = condition
			} else {
				// Keep existing transition time, update other fields
				dashboard.Status.Conditions[i].Reason = reason
				dashboard.Status.Conditions[i].Message = message
				dashboard.Status.Conditions[i].ObservedGeneration = dashboard.Generation
			}
			found = true
			break
		}
	}

	if !found {
		dashboard.Status.Conditions = append(dashboard.Status.Conditions, condition)
	}

	// Use status subresource to update only status
	return r.Status().Update(ctx, dashboard)
}

// calculateHash generates a hash of the dashboard content for change detection
func calculateHash(content string) string {
	// In a real implementation, use crypto/sha256
	// This is a placeholder
	return fmt.Sprintf("hash-%d", len(content))
}

// ============================================================================
// Controller Setup
// ============================================================================

// SetupWithManager sets up the controller with the Manager.
// This configures:
// - What resources to watch
// - Event filters (predicates)
// - Concurrent reconciliation settings
func (r *GrafanaDashboardReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		// Primary resource to watch
		For(&observabilityv1alpha1.GrafanaDashboard{}).
		// Watch ConfigMaps that are referenced by dashboards
		// This triggers reconciliation when a referenced ConfigMap changes
		Owns(&corev1.ConfigMap{}).
		// Filter events to reduce unnecessary reconciliations
		WithEventFilter(predicate.Or(
			// Always process create/delete events
			predicate.GenerationChangedPredicate{},
			// Process annotation changes (for manual triggers)
			predicate.AnnotationChangedPredicate{},
		)).
		// Complete the setup
		Complete(r)
}

// ============================================================================
// Main Function (Entry Point)
// ============================================================================

// This would typically be in cmd/main.go
// Included here for completeness

/*
func main() {
	// Setup logging
	opts := zap.Options{
		Development: true,
	}
	ctrl.SetLogger(zap.New(zap.UseFlagOptions(&opts)))

	// Create the manager
	mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
		Scheme:                 scheme,
		MetricsBindAddress:     ":8080",
		Port:                   9443,
		HealthProbeBindAddress: ":8081",
		LeaderElection:         true,
		LeaderElectionID:       "grafana-dashboard-operator.observability.grafana.com",
	})
	if err != nil {
		setupLog.Error(err, "unable to start manager")
		os.Exit(1)
	}

	// Setup the controller
	if err = (&GrafanaDashboardReconciler{
		Client:        mgr.GetClient(),
		Scheme:        mgr.GetScheme(),
		Log:           ctrl.Log.WithName("controllers").WithName("GrafanaDashboard"),
		Recorder:      mgr.GetEventRecorderFor("grafana-dashboard-controller"),
		GrafanaClient: NewGrafanaClient(), // Your Grafana API client
	}).SetupWithManager(mgr); err != nil {
		setupLog.Error(err, "unable to create controller", "controller", "GrafanaDashboard")
		os.Exit(1)
	}

	// Add health checks
	if err := mgr.AddHealthzCheck("healthz", healthz.Ping); err != nil {
		setupLog.Error(err, "unable to set up health check")
		os.Exit(1)
	}
	if err := mgr.AddReadyzCheck("readyz", healthz.Ping); err != nil {
		setupLog.Error(err, "unable to set up ready check")
		os.Exit(1)
	}

	// Start the manager
	setupLog.Info("starting manager")
	if err := mgr.Start(ctrl.SetupSignalHandler()); err != nil {
		setupLog.Error(err, "problem running manager")
		os.Exit(1)
	}
}
*/

// ============================================================================
// API Types (Would be in api/v1alpha1/grafanadashboard_types.go)
// ============================================================================

// These types would normally be generated by kubebuilder
// Included here for reference

/*
// GrafanaDashboard is the Schema for the grafanadashboards API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Title",type=string,JSONPath=`.spec.title`
// +kubebuilder:printcolumn:name="Synced",type=string,JSONPath=`.status.conditions[?(@.type=="Synced")].status`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`
type GrafanaDashboard struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   GrafanaDashboardSpec   `json:"spec,omitempty"`
	Status GrafanaDashboardStatus `json:"status,omitempty"`
}

// GrafanaDashboardSpec defines the desired state of GrafanaDashboard
type GrafanaDashboardSpec struct {
	Title            string                    `json:"title,omitempty"`
	Folder           string                    `json:"folder,omitempty"`
	JSON             string                    `json:"json,omitempty"`
	JSONDataFrom     *JSONDataFrom             `json:"jsonDataFrom,omitempty"`
	URL              string                    `json:"url,omitempty"`
	GrafanaCom       *GrafanaComDashboard      `json:"grafanaCom,omitempty"`
	Datasources      []DatasourceMapping       `json:"datasources,omitempty"`
	InstanceSelector *metav1.LabelSelector     `json:"instanceSelector"`
	Plugins          []PluginRequirement       `json:"plugins,omitempty"`
	ResyncPeriod     string                    `json:"resyncPeriod,omitempty"`
}

// GrafanaDashboardStatus defines the observed state of GrafanaDashboard
type GrafanaDashboardStatus struct {
	UID                string             `json:"uid,omitempty"`
	URL                string             `json:"url,omitempty"`
	ContentHash        string             `json:"contentHash,omitempty"`
	LastSyncTime       *metav1.Time       `json:"lastSyncTime,omitempty"`
	Conditions         []metav1.Condition `json:"conditions,omitempty"`
	ObservedGeneration int64              `json:"observedGeneration,omitempty"`
}
*/
